server:
  port: 8088

spring:
  #redis
  redis:
    host: localhost
    port: 6379
  #thymeleaf配置
  thymeleaf:
    #关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rgks?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空间连接出
      minimum-idle: 5
      #空闲连接存活最大时间（默认60000十分钟）
      idle-timeout: 180000
      #最大连接数，默认10
      miximum-pool-size: 10
      #从连接池返回自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认180000（30分钟）
      max-lifetime: 180000
      #连接超时时间
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

#mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.example.rgks_rear.pojo

#mybatis sql 打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.example.rgks_rear.mapper: debug

